opentracing/opentracing-java

- opentracing/src/main/java/opentracing/Tracer.java
See https://github.com/opentracing/opentracing-java/pull/10/files#r54330197
> Tracer.startSpan(..) with a builder for specifying the arguments

- opentracing/src/main/java/io/opentracing/Span.java
- opentracing/src/main/java/io/opentracing/Tracer.java
- opentracing/src/main/java/io/opentracing/noop/NoopSpan.java
- opentracing/src/main/java/io/opentracing/noop/NoopSpanBuilder.java
- opentracing/src/main/java/io/opentracing/noop/NoopTracer.java
- opentracing/src/test/java/io/opentracing/PlaygroundTest.java
- rename packages to be io.opentracing
- add noop Tracer, Span, and SpanBuilder
> add noop, and rename package

- opentracing/src/main/java/io/opentracing/noop/NoopSpan.java
- opentracing/src/main/java/io/opentracing/noop/NoopSpanBuilder.java
- opentracing/src/main/java/io/opentracing/noop/NoopTracer.java
- made noop constants static and final
- made noop classes final
> fixed noop tracer

- opentracing-api/src/main/java/io/opentracing/propagation/TextMap.java
- opentracing-api/src/main/java/io/opentracing/propagation/TextMapExtractAdapter.java
- opentracing-api/src/main/java/io/opentracing/propagation/TextMapInjectAdapter.java
- opentracing-impl-java8/src/test/java/io/opentracing/propagation/TestTextMapExtractorImpl.java
cc @maxwindiff @adriancole 
... and c.f. https://gitter.im/opentracing/public?at=57a38773836d2d021164513f
> Support Iterable via a method rename

- opentracing-api/src/main/java/io/opentracing/Span.java
- opentracing-impl-java8/src/main/java/io/opentracing/AbstractSpan.java
- opentracing-impl/src/main/java/io/opentracing/NoopSpan.java
Somehow this feature (present in all other languages) was missing :-/
> Support explicit Span finish times

- opentracing-api/src/main/java/io/opentracing/Span.java
- opentracing-api/src/main/java/io/opentracing/Tracer.java
- opentracing-impl-java8/src/main/java/io/opentracing/AbstractSpan.java
- opentracing-impl/src/main/java/io/opentracing/NoopSpan.java
- opentracing-mock/src/main/java/io/opentracing/mock/MockSpan.java
> Add Span#setOperationName

- opentracing-api/src/main/java/io/opentracing/tag/Tags.java
@adriancole @bensigelman could you please review?
> Add http.method to standard tags

- opentracing-mock/src/main/java/io/opentracing/mock/MockTracer.java
@bensigelman @yurishkuro could you please review? 
https://github.com/opentracing/opentracing-java/issues/74
> MockTracer onSpanFinished

- opentracing-mock/src/main/java/io/opentracing/mock/MockTracer.java
@bensigelman could you please review? See https://github.com/opentracing/opentracing-java/pull/76#issuecomment-267914245
> Allow to override MockTracer

- opentracing-api/pom.xml
- opentracing-impl/pom.xml
- opentracing-mock/pom.xml
- opentracing-noop/pom.xml
- pom.xml
@bensigelman this should fix licenses in `pom.xml`.
(hint `mvn license:format`)
> Enable license plugin in pom.xml

- opentracing-mock/src/main/java/io/opentracing/mock/MockSpan.java
@bensigelman could you please review?
> MockSpan make finish operation idempotent

- opentracing-mock/src/main/java/io/opentracing/mock/MockTracer.java
- opentracing-mock/src/test/java/io/opentracing/mock/MockTracerTest.java
It would be good to provide default `TextMap` propagator for `MockTracer`. I'm rewriting this code in all instrumentation tests.  
@yurishkuro @bensigelman could you please review?
> MockTracer TextMap propagator

- opentracing-api/src/main/java/io/opentracing/tag/AbstractTag.java
- opentracing-api/src/main/java/io/opentracing/tag/BooleanTag.java
- opentracing-api/src/main/java/io/opentracing/tag/IntTag.java
- opentracing-api/src/main/java/io/opentracing/tag/ShortTag.java
- opentracing-api/src/main/java/io/opentracing/tag/StringTag.java
- opentracing-api/src/main/java/io/opentracing/tag/Tags.java
Allow users to define framework/app... specific tags.
> Allow consumers to define tags

- opentracing-api/src/main/java/io/opentracing/tag/Tags.java
Adding tag related to https://github.com/opentracing/specification/pull/49.
> Add the 'message_bus.destination' tag

- travis/publish.sh
This is the format @bhs tried to use. I've seen `0.0.0.RC1` from the spring projects so I'm not sure which would make more sense to people
> Add RC releasing to travis publish script

- opentracing-mock/src/main/java/io/opentracing/mock/MockTracer.java
- opentracing-mock/src/test/java/io/opentracing/mock/MockTracerTest.java
Implementation and tests to propagate baggage items in MockTracer.Propagator.TEXT_MAP
> Mock baggage

- RELEASE.md
- travis/publish.sh
> Readme document release process for release candidates

- opentracing-util/pom.xml
- opentracing-util/src/test/java/io/opentracing/util/GlobalTracerTest.java
- opentracing-util/src/test/java/io/opentracing/util/GlobalTracerTestUtil.java
This may help people needing to reset the GlobalTracer (see #170).
> Globaltracer testutil

- README.md
- opentracing-api/src/main/java/io/opentracing/ScopeManager.java
Fix review comments from https://github.com/opentracing/opentracing-java/pull/219#pullrequestreview-81868485 
cc @carlosalberto
> Fix readme and docs about scope manager

- opentracing-examples/README.md
- opentracing-examples/src/test/java/io/opentracing/examples/activate_deactivate/README.md
- opentracing-examples/src/test/java/io/opentracing/examples/active_span_replacement/README.md
- opentracing-examples/src/test/java/io/opentracing/examples/actor_propagation/README.md
- opentracing-examples/src/test/java/io/opentracing/examples/client_server/README.md
- opentracing-examples/src/test/java/io/opentracing/examples/common_request_handler/README.md
- opentracing-examples/src/test/java/io/opentracing/examples/late_span_finish/LateSpanFinishTest.java
- opentracing-examples/src/test/java/io/opentracing/examples/late_span_finish/README.md
- opentracing-examples/src/test/java/io/opentracing/examples/listener_per_request/README.md
- opentracing-examples/src/test/java/io/opentracing/examples/multiple_callbacks/README.md
- opentracing-examples/src/test/java/io/opentracing/examples/nested_callbacks/README.md
- opentracing-examples/src/test/java/io/opentracing/examples/promise_propagation/README.md
- opentracing-examples/src/test/java/io/opentracing/examples/suspend_resume_propagation/README.md
Add a README to each example, to briefly describe what is being tested in each one. Expands a little bit the current available information in the top-level README (which now links to them as well).
Let me know - either in description improvements or wording itself ;)
References #240 ;)
> Examples descriptions

- opentracing-api/src/main/java/io/opentracing/Span.java
- opentracing-api/src/main/java/io/opentracing/Tracer.java
While reading the code to get https://github.com/opentracing/opentracing-php/pull/45 working I found a couple of references we should change in order to keep consistency in the code.
Ping @yurishkuro @tedsuo
> Fixes startManual references.

- README.md
It actually compiles now and also includes how to log an exception
> Fix try/catch/finally example

- opentracing-api/pom.xml
- opentracing-mock/pom.xml
- opentracing-noop/pom.xml
- opentracing-testbed/pom.xml
- opentracing-util/pom.xml
- pom.xml
This PR is intended to fix #308
> Set version in `v0.32.0` branch to `0.32.0-SNAPSHOT`
