- opentracing/src/main/java/opentracing/Span.java
Simplify the logging and timestamped annotations down to a `event(message, payload)` method.
Rationale:
This is the simplest solution, and an appropriate plumbing API, that solves the use-case of
info/error and parameterised message formatting.
OpenTracing API may adopt a porcelain API for those info/error logging-style methods down the road once the plumbing api has been battle tested a bit more.
(cherry picked from commit 5630ab2389e054f9a353b35642acb87eac5cd00c)
> Simplify the API: logging and timestamped annotations

- .settings.xml
- .travis.yml
- RELEASE.md
- opentracing-api/pom.xml
- opentracing-impl-java8/pom.xml
- opentracing-impl/pom.xml
- pom.xml
- travis/publish.sh
This re-uses the deployment flow from zipkin-java which has the
following features:
* Makes OpenTracing Java releaseable by anyone with access to the Bintray org
* Snapshot publishing to http://oss.jfrog.org/artifactory/oss-snapshot-local
* Fully automated release to maven central via release-N.N.N tag
* Releases also published to https://jcenter.bintray.com
Fixes #3
> Adds tag-based publishing to Maven Central

- opentracing-api/src/main/java/io/opentracing/Span.java
- opentracing-api/src/main/java/io/opentracing/SpanContext.java
- opentracing-impl-java8/src/main/java/io/opentracing/AbstractSpanBuilder.java
- opentracing-impl-java8/src/test/java/io/opentracing/AbstractTracerTest.java
- opentracing-impl-java8/src/test/java/io/opentracing/TestSpanContextImpl.java
- opentracing-impl-java8/src/test/java/io/opentracing/TestSpanImpl.java
- opentracing-impl/src/main/java/io/opentracing/NoopSpan.java
Per https://github.com/opentracing/opentracing.github.io/issues/106
This change has already happened in Go and Python.
> Move to the immutable SpanContext model

- opentracing-impl/src/main/java/io/opentracing/NoopTracer.java
All other classes in this package expose singletons, any reason not to do the same for NoopTracer?
> Expose public singleton instance of NoopTracer

- opentracing-impl-java8/src/main/java/io/opentracing/AbstractSpan.java
- opentracing-impl-java8/src/test/java/io/opentracing/AbstractTracerTest.java
- opentracing-impl-java8/src/test/java/io/opentracing/TestTextMapInjectorImpl.java
Tags and start time were not visible to concrete span implementations. Operation was public. So thought would make all protected so were consistent (with exception of duration as created under control of the abstract span).
If you would prefer accessors let me know.,
> Make the fields in the abstract span available to concrete impls

- opentracing-api/pom.xml
- opentracing-api/src/test/java/io/opentracing/AssertionTest.java
- opentracing-impl/pom.xml
- opentracing-impl/src/main/java/io/opentracing/impl/AbstractSpan.java
- opentracing-impl/src/main/java/io/opentracing/impl/AbstractSpanBuilder.java
- opentracing-impl/src/main/java/io/opentracing/impl/AbstractTracer.java
- opentracing-impl/src/main/java/io/opentracing/impl/NoopSpan.java
- opentracing-impl/src/main/java/io/opentracing/impl/NoopSpanBuilder.java
- opentracing-impl/src/main/java/io/opentracing/impl/NoopTracer.java
- opentracing-impl/src/main/java/io/opentracing/impl/TextMapExtractorImpl.java
- opentracing-impl/src/main/java/io/opentracing/impl/TextMapInjectorImpl.java
- opentracing-impl/src/test/java/io/opentracing/impl/AbstractTracerTest.java
- opentracing-impl/src/test/java/io/opentracing/impl/TestSpanBuilder.java
- opentracing-impl/src/test/java/io/opentracing/impl/TestSpanImpl.java
- opentracing-impl/src/test/java/io/opentracing/impl/TestTextMapExtractorImpl.java
- opentracing-impl/src/test/java/io/opentracing/impl/TestTextMapInjectorImpl.java
- opentracing-mock/pom.xml
- opentracing-noop/pom.xml
- opentracing-noop/src/main/java/io/opentracing/NoopSpan.java
- opentracing-noop/src/main/java/io/opentracing/NoopSpanBuilder.java
- opentracing-noop/src/main/java/io/opentracing/NoopSpanContext.java
- opentracing-noop/src/main/java/io/opentracing/NoopTracer.java
- opentracing-noop/src/main/java/io/opentracing/NoopTracerFactory.java
- pom.xml
A child of a NoopSpan is a NoopSpan (without explicit forced sampling).
If a NoopSpan or Noop SpanContext is declared as a parent to the span during the SpanBuilder usage, then return the NoopSpanBuilder. This has been re-implemented so that a) Noop objects are separate entities in the opentracing landscape which can not be mix-and-matched, and b) can re-use them by concept so to enable fluent APIs (ie avoiding nulls being passed around).
**Actions**
Merge impl and impl-java8 to avoid confusion regarding their roles.
Move Noop classes to their own component "opentracing-noop" where they can't be confused to be part of, or mix-and-matched with, the impl classes.
Move the Noop classes into interfaces, while creating default implementations of this. This (along with using the create() …
> Fixes class cast exception , and Solves #45

- opentracing-api/pom.xml
- opentracing-api/src/main/java/io/opentracing/propagation/Format.java
The source code of opentracing-api is just interface or abstract class for OpenTracing specification. Is it necessary use jdk 1.7 to build? 
I also check the release version on `The Central Repository`, class file is also build by JDK 1.7
Many projects use opentracing.io specification in order to build trace system, which is using javaagent tech. Such as [sky-walking](https://github.com/wu-sheng/sky-walking)  (I am working on it). It's jdk level must match to target app. Also  we will support jdk 1.6, 1.7 and 1.8 .
Official opentracing-api should release on jdk 1.6. Is this look good to you?
> support opentracing-api module in jdk 1.6

- opentracing-impl/src/main/java/io/opentracing/impl/AbstractSpanBuilder.java
- opentracing-impl/src/test/java/io/opentracing/impl/AbstractTracerTest.java
The specification says that baggage is ["propagated in-band to all child
Spans and their SpanContexts"](http://opentracing.io/documentation/pages/spec.html#baggage).
This PR makes AbstractSpanBuilder copy baggage from a parent Span or SpanContext when creating a child Span.
> Propagate baggage to child spans

- opentracing-impl/src/main/java/io/opentracing/impl/TextMapInjectorImpl.java
SpanContext already has the baggageItems() method.
> Remove an unnecessary cast. 

- opentracing-api/src/main/java/io/opentracing/References.java
- opentracing-api/src/main/java/io/opentracing/Span.java
- opentracing-impl/src/main/java/io/opentracing/impl/AbstractSpanBuilder.java
- AbstractSpanBuilder did unnecessary (and unsafe!) cast to AbstractSpan that was not necessary.
- Span implements AutoCloseable which is only available since Java7 while project delcares Java6.
Changed to Closeable which also extends AutoCloseable and doesn't declare additional methods
so is 100% compatible and Java6 compliant.
- Fixed broken @see link in Reference class javadoc.
> Possible ClassCastException fix in AbstractSpanBuilder + API fixes.

- opentracing-api/src/main/java/io/opentracing/Tracer.java
Fixed the {@link} for the `boolean` and `Number` methods.
> Very minor JavaDoc fix for SpanBuilder.withTag() methods.

- opentracing-mock/src/main/java/io/opentracing/mock/MockSpan.java
- opentracing-mock/src/main/java/io/opentracing/mock/MockTracer.java
- opentracing-mock/src/test/java/io/opentracing/mock/MockTracerTest.java
@adriancole @bensigelman could you please review?
> MockSpan fix startMicros to implicit value

- opentracing-mock/src/main/java/io/opentracing/mock/MockSpan.java
- opentracing-mock/src/main/java/io/opentracing/mock/MockTracer.java
- opentracing-mock/src/test/java/io/opentracing/mock/MockTracerTest.java
`MockTracer.SpanBuilder` has package level visibility. It cannot be used in different packages (`io.opentracing.mock`) . It makes it hard to test instrumentation libraries which are usually in different packages.
Q:
`MockContext` should be probably also public. It is needed when implementing custom `MockTracer.Propagator` (which a paramter in `MockTracer` public constructor).
@yurishkuro @bensigelman could you please review?
> Make MockSpanBuilder public so it can be used in different packages

- opentracing-noop/pom.xml
As the API is explicitly defined as java 1.6, there is no reason why noop implementation should also not be build in v1.6, especially that there is nothing out there that would represent a problem for such thing. Thus I simply updated the ```pom.xml``` to overwrite the default setting from the main pom.
> Noop implementation should be in java version 1.6

- opentracing-mock/src/main/java/io/opentracing/mock/MockSpan.java
- opentracing-mock/src/test/java/io/opentracing/mock/MockSpanTest.java
call to any method after `finish` is undefined, therefore for testing purposes I find it useful to throw an exception if such situation happens.
> MockSpan throw an exception when setting data on finished span

- opentracing-api/src/main/java/io/opentracing/tag/Tags.java
Based on OT spec update:
```yaml
#####################################################################
#####################################################################
'db.type':
type: string
comment: 'Database type'
examples: 'For any SQL database, "sql". For others, the lower-case database category, e.g. "cassandra", "hbase", or "redis".'
'db.instance':
type: string
comment: 'Database instance name'
examples: 'In java, if the jdbc.url="jdbc:mysql://127.0.0.1:3306/customers", instance name is "customers".'
'db.user':
type: string
comment: 'Username for accessing database'
examples: '"readonly_user" or "reporting_user"'
'db.statement':
type: string
comment: 'A database statement for the given database type.'
examples: 'For db.type="SQL", "SELECT * FROM wuser_table". For …
```
> Add new tags based on OT spec update.

- opentracing-mock/src/main/java/io/opentracing/mock/MockTracer.java
Currently in tests when one is building a span he has to cast it be able to access `MockSpan` attributes.
```
MockSpan parent = (MockSpan) mockTracer.buildSpan("foo")
.start();
```
a generic builder would be better but probably you have already discussed it.
@bensigelman @yurishkuro @michaelsembwever  could you please review?
> MockSpanBuilder return its type not Tracer.SpanBuilder

- opentracing-mock/src/main/java/io/opentracing/mock/MockSpan.java
`MockSpan#toString()` for debug purposes. It also simplifies implementation of "`LoggingTracer`"
```java
class LoggingTracer extends MockTracer {
protected void onSpanFinished(MockSpan mockSpan) {
System.out.println(mockSpan);
}
}
```
It closes https://github.com/opentracing/opentracing-java/issues/82
> MockSpan toString method

- opentracing-api/src/main/java/io/opentracing/Tracer.java
Parts of it were 2-space rather than 4-space.
This led to noisy diffs in https://github.com/opentracing/opentracing-java/pull/111 .
I'm just going to merge this – surely it's [not controversial](https://www.youtube.com/watch?v=SsoOG6ZeyUI)!
> Fix Tracer.java indenting

- opentracing-api/src/main/java/io/opentracing/tag/Tags.java
Set `peer.port` as a short, is not right. As mentioned #113 , in Java, short is -32768 to 32767, but in network world, port is 0 to 65535.
> Change peer.port to integer.

- opentracing-noop/src/main/java/io/opentracing/NoopSpan.java
- opentracing-noop/src/main/java/io/opentracing/NoopSpanBuilder.java
- opentracing-noop/src/main/java/io/opentracing/NoopSpanContext.java
- opentracing-noop/src/main/java/io/opentracing/NoopTracer.java
The [GlobalTracer PR](https://github.com/opentracing/opentracing-java/pull/109/commits/dc3550b7027627e295776be27387c6b1d1ee5a44) added its delegate tracer to the toString representation which is initially the NoopTracer.
The standard Java toString is the fully qualified classname (i.e. `io.opentracing.NoopSpanImpl`) followed by its hashcode (which is irrelevant for a singleton).
Therefore I suggest using `NoopSpan`, `NoopSpanBuilder`, `NoopSpanContext` and `NoopTracer` as their toString() representations.
> Add toString() to no-op implementations.

- opentracing-api/src/main/java/io/opentracing/SpanContext.java
- opentracing-api/src/main/java/io/opentracing/propagation/Format.java
- opentracing-api/src/main/java/io/opentracing/propagation/TextMapExtractAdapter.java
- opentracing-api/src/main/java/io/opentracing/propagation/TextMapInjectAdapter.java
Carving this out of #115 to reduce noise in the diff per @yurishkuro's request.
> Make javadoc work and update license headers

- opentracing-api/src/main/java/io/opentracing/tag/ShortTag.java
- opentracing-api/src/main/java/io/opentracing/tag/Tags.java
It is inconvenient to use `short` for this. It's a breaking change but I think it's cleaner/easier to use `integer`.
Spec defines it as an `integer` https://github.com/opentracing/specification/blob/master/semantic_conventions.yaml#L26
> Define tag SAMPLING_PRIORITY as an integer

- CONTRIBUTING.md
- opentracing-api/src/main/java/io/opentracing/References.java
- opentracing-api/src/main/java/io/opentracing/propagation/TextMap.java
- opentracing-api/src/test/java/io/opentracing/tag/BooleanTagTest.java
- opentracing-api/src/test/java/io/opentracing/tag/IntTagTest.java
- opentracing-api/src/test/java/io/opentracing/tag/ShortTagTest.java
- opentracing-api/src/test/java/io/opentracing/tag/StringTagTest.java
- opentracing-noop/src/main/java/io/opentracing/NoopTracerFactory.java
The license plugin runs locally (and ran on updates to PR #115) but isn't working now that it's merged. This should resolve that.
> Force all years to 2017

- opentracing-util/README.md
The `opentracing-contrib/java-globaltracer` repo had a README explaining the GlobalTracer.
Although the JavaDoc was moved along with the code to `opentracing-util`, the README hadn't yet been copied.
> Document GlobalTracer in opentracing-util

- opentracing-api/src/main/java/io/opentracing/Span.java
The imports for `Closeable` and `Map` were no longer used.
> Remove unnecessary imports from Span.java.

- README.md
- opentracing-util/src/main/java/io/opentracing/util/GlobalTracer.java
Inasmuch as a singleton mechanism is needed in some places, it ought to be part of OT-Java's core API. That said, it's not a recommended best practice when more modern options are available.
Closes #140.
> Qualify use of GlobalTracer

- opentracing-mock/src/main/java/io/opentracing/mock/MockTracer.java
- opentracing-noop/src/main/java/io/opentracing/noop/NoopActiveSpanSource.java
- opentracing-noop/src/main/java/io/opentracing/noop/NoopSpan.java
- opentracing-noop/src/main/java/io/opentracing/noop/NoopSpanBuilder.java
- opentracing-noop/src/main/java/io/opentracing/noop/NoopSpanContext.java
- opentracing-noop/src/main/java/io/opentracing/noop/NoopTracer.java
- opentracing-noop/src/main/java/io/opentracing/noop/NoopTracerFactory.java
- opentracing-util/src/main/java/io/opentracing/util/GlobalTracer.java
- opentracing-util/src/test/java/io/opentracing/util/GlobalTracerTest.java
Signed-off-by: Tomas Kraus <tomas.kraus@oracle.com>
> Fixes #145 - Rename package in opentracing-noop to io.opentracing.noop

- opentracing-api/src/main/java/io/opentracing/log/Fields.java
> Add constants for log fields

- travis/publish.sh
A recent change to the ./mvnw script changed output slightly and broke
the logic which detected versions. This fixes it.
This should be applied to anything that uses this script
> Fixes release pattern

- opentracing-api/src/main/java/io/opentracing/tag/IntOrStringTag.java
- opentracing-api/src/main/java/io/opentracing/tag/Tags.java
I am creating a new pull request for #163. It is for #162 . And taken @yurishkuro 's suggestion.
> Provide a new Tag for PEER_HOST_IPV4

- travis/publish.sh
This should allow releasing from any `digit.digit.digit` branch. This uses `0.0.0-RC0` pattern for releases. 
To release switch to the `0.31.0` branch tag `release-0.31.0-RC1` and push to upstream.
cc @tedsuo
> travis publish.sh allow releases from branches

- travis/publish.sh
Publis script compares remote branch with current checkout.
This passes travis_branch into git checkout command so
it will compare the same branches.
This is related to #191 , The build failed https://travis-ci.org/opentracing/opentracing-java/builds/279837722#L1176
> Travis allow release from non master branches

- travis/publish.sh
Thre previous build didn't deploy artifact to maven. It just bumped versions and created branch `0.31.0-RC1`
> Travis publish script, remove -RC on git checkout

- travis/publish.sh
Thing is, we cannot publish from 0.0.0-style branches as they are
excluded, based on the current global Travis configuration, thus
we try to publish from branches following a v.0.0.0 style, if any.
> Update the Travis script to allow publishing from v.0.0.0 branches.

- opentracing-mock/src/main/java/io/opentracing/mock/MockTracer.java
- opentracing-noop/src/main/java/io/opentracing/noop/NoopSpanBuilder.java
- Propagate @deprecated annotation to implementations
- Remove redundant "static final" definition from interface
- Use Collections.emptyMap instead of Collections.EMPTY_MAP to preserve type
> Code cleanup (for master)

- opentracing-mock/src/main/java/io/opentracing/mock/MockTracer.java
- opentracing-mock/src/test/java/io/opentracing/mock/MockSpanTest.java
- opentracing-mock/src/test/java/io/opentracing/mock/MockTracerTest.java
According to [SpanBuilder interface](https://github.com/opentracing/opentracing-java/blob/master/opentracing-api/src/main/java/io/opentracing/Tracer.java#L106), `ChildOf` called with `null` parent should be a noop. This pull request fixes this behaviour for MockTracer.
> Make MockTracer::ChildOf not fail if there is a null argument passed

- opentracing-api/src/main/java/io/opentracing/Tracer.java
- opentracing-mock/src/main/java/io/opentracing/mock/MockTracer.java
- opentracing-mock/src/test/java/io/opentracing/mock/MockTracerTest.java
- opentracing-noop/src/main/java/io/opentracing/noop/NoopTracer.java
- opentracing-util/src/main/java/io/opentracing/util/GlobalTracer.java
This is a small PR intended to address #227 as a way to provide a shorthand for getting the active span from a `Tracer`.
One alternative would have been to have `Tracer.activeScope()` but that would only save us from typing `scopeManager()`, so not much save here.
> Let Tracer.activeSpan() be a shorthand for ScopeManager's active Span.

- opentracing-api/src/main/java/io/opentracing/Tracer.java
Related to https://github.com/opentracing/opentracing-java/issues/222#issuecomment-347887141 and https://github.com/opentracing/opentracing-java/pull/219#issuecomment-348088037
> SpanBuilder deprecate startManual

- opentracing-api/src/main/java/io/opentracing/propagation/Format.java
Format.java specifies a carrier, but then refers to a non-existant reader in the Javadoc example.  Changed to use carrier.
> Use correct reference in io.opentracing.propagation.Format Javadoc

- opentracing-mock/src/main/java/io/opentracing/mock/MockTracer.java
- opentracing-mock/src/test/java/io/opentracing/mock/MockTracerTest.java
> MockTracer use text map propag as default constructor

- README.md
Update our README to point users to the 0.30 compatibility package.
> Mention the 0.30 compatibility package in the README.

- opentracing-examples/src/test/java/io/opentracing/examples/activate_deactivate/RunnableAction.java
- opentracing-examples/src/test/java/io/opentracing/examples/activate_deactivate/ScheduledActionsTest.java
- opentracing-examples/src/test/java/io/opentracing/examples/multiple_callbacks/Client.java
- opentracing-examples/src/test/java/io/opentracing/examples/multiple_callbacks/MultipleCallbacksTest.java
- opentracing-util/src/main/java/io/opentracing/util/AutoFinishScope.java
- opentracing-util/src/main/java/io/opentracing/util/AutoFinishScopeManager.java
- opentracing-util/src/test/java/io/opentracing/util/AutoFinishScopeManagerTest.java
- opentracing-util/src/test/java/io/opentracing/util/AutoFinishScopeTest.java
Creating this PR in order to move the `AutoFinishScopeManager` from the examples module into the util one, so this can be accessible to other libraries (even if we don't support the `Continuation` concept out of the box anymore).
I'm playing with this possibility as both the v030 and the akka support will optionally offer this flavor of `ScopeManager`, and thought it could be helpful for other people/projects overall.
Opinions on this? Shall we put it here and expose it publicly?
> Auto finish scope manager

- opentracing-api/src/main/java/io/opentracing/tag/StringTag.java
It's not a common scenario to use a Tag *key* as the tag value. Would fix #229
> Deprecate the StringTag.set() overload taking a StringTag.

- opentracing-mock/src/main/java/io/opentracing/mock/MockTracer.java
Currently, the no-argument constructor for the MockTracer uses a `ThreadLocalScopeManager`
and a `Propagator.TEXT_MAP` as default values. But when providing a Propagator,
the constructor injects a `NoopScopeManager` instead of the `ThreadLocalScopeManager`.
This commit brings the Propagator constructor closer into line with the default
values for this mock.
cc: @yurishkuro
Signed-off-by: Nate Hart <nhart@tableau.com>
> Updating the Mock Tests To Use Proper Scope Manager

- opentracing-noop/src/main/java/io/opentracing/noop/NoopScopeManager.java
- opentracing-noop/src/main/java/io/opentracing/noop/NoopTracer.java
- opentracing-noop/src/test/java/io/opentracing/noop/NoopScopeManagerTest.java
- opentracing-noop/src/test/java/io/opentracing/noop/NoopTracerTest.java
In special circumstances, code may automatically generate spans,
negating the need to always check if `Tracer.activeSpan()` is `null`. Under these
circumstances, the Noop Tracer and ScopeManager will cause NPEs when they return
`null` values when their `active` methods are accessed via the GlobalTracer. This
prevents code from running successfully when using Noop Tracers.
This minor change allows users to depend that their code will genuinely Noop
under all use cases.
Signed-off-by: Nate Hart <nhart@tableau.com>
> Enabling NOOP classes to work with pre-existing production code

- opentracing-api/src/main/java/io/opentracing/Tracer.java
See https://github.com/opentracing/opentracing-java/issues/168
https://github.com/opentracing/opentracing-java/pull/203
There are two proposed changes in the above issue:
- Documenting that Tracer#extract can return null (many tracer impls are already doing this)
- Adding `@Nullable` annotation to `extract` to assist static checkers
This PR only addresses the doc change. The annotation will be proposed in a separate PR.
> Document that Tracer#extract can return null

- opentracing-api/src/main/java/io/opentracing/tag/Tags.java
Related to https://github.com/opentracing/specification/issues/77 and https://github.com/opentracing/specification/pull/119
Signed-off-by: Pavol Loffay <ploffay@redhat.com>
> Add service tag

- opentracing-noop/src/main/java/io/opentracing/noop/NoopSpanBuilder.java
- opentracing-noop/src/main/java/io/opentracing/noop/NoopTracer.java
Would fix #255 
@yurishkuro ;)
> NoopSpanBuilder does not need to inherit from SpanContext.

- pom.xml
Before this change, building this library with a Java 10 JDK results in a failure, such as:
```
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ opentracing-api ---
[INFO] Surefire report directory: /mnt/storage/jpkroehling/Projects/src/github.com/opentracing/opentracing-java/opentracing-api/target/surefire-reports
-------------------------------------------------------
T E S T S
-------------------------------------------------------
Exception in thread "main" java.lang.reflect.InvocationTargetException
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorI …
```
> Bump JaCoCo to use a Java 10 friendly version

- opentracing-api/src/main/java/io/opentracing/Span.java
- opentracing-api/src/main/java/io/opentracing/Tracer.java
- opentracing-mock/src/main/java/io/opentracing/mock/MockSpan.java
- opentracing-mock/src/main/java/io/opentracing/mock/MockTracer.java
- opentracing-noop/src/main/java/io/opentracing/noop/NoopSpan.java
- opentracing-noop/src/main/java/io/opentracing/noop/NoopSpanBuilder.java
Reduces the need to call Tags.SOMETAG.getKey() and adds type safety for setTag if done from the span.
Fixes #271
> Add generic typed setTag/withTag

- opentracing-api/src/main/java/io/opentracing/propagation/TextMapInjectAdapter.java
- opentracing-api/src/test/java/io/opentracing/propagation/TextMapInjectAdapterTest.java
For the inject case, it doesn’t matter so much that the generic type is declared as String.
> Allow injecting into maps of type Map<String,Object>

- opentracing-api/src/main/java/io/opentracing/Span.java
- opentracing-api/src/main/java/io/opentracing/Tracer.java
- opentracing-api/src/main/java/io/opentracing/tag/AbstractTag.java
- opentracing-api/src/main/java/io/opentracing/tag/Tag.java
- opentracing-mock/src/main/java/io/opentracing/mock/MockSpan.java
- opentracing-mock/src/main/java/io/opentracing/mock/MockTracer.java
- opentracing-noop/src/main/java/io/opentracing/noop/NoopSpan.java
- opentracing-noop/src/main/java/io/opentracing/noop/NoopSpanBuilder.java
This is done to not use an abstract class for our public API,
so we take overloads of BooleanTag, IntTag and StringTag.
Addresses a small detail mentioned in #314 
@yurishkuro @tylerbenson
> Do not use AbstractTag<T> for Span.setTag(), but the actual impls.

- opentracing-util/src/main/java/io/opentracing/util/GlobalTracer.java
- opentracing-util/src/test/java/io/opentracing/util/GlobalTracerTest.java
- pom.xml
Resolves https://github.com/opentracing/opentracing-java/issues/286
Signed-off-by: Pavol Loffay <ploffay@redhat.com>
> Add simple registerIfAbsent to global tracer

- opentracing-api/src/main/java/io/opentracing/tag/Tags.java
See https://github.com/opentracing/specification/issues/131.
Until this gets resolved, I don't think it should be included in an official release.
Reverts opentracing/opentracing-java#287.
Note, this is being merged into the `v0.32.0` feature branch to be part of the next RC.
> Revert PR 287 which added service tag

- opentracing-api/src/main/java/io/opentracing/propagation/BinaryAdapters.java
- opentracing-api/src/main/java/io/opentracing/propagation/BinaryExtract.java
- opentracing-api/src/main/java/io/opentracing/propagation/BinaryInject.java
- opentracing-api/src/main/java/io/opentracing/propagation/Format.java
- opentracing-api/src/main/java/io/opentracing/propagation/TextMap.java
- opentracing-api/src/main/java/io/opentracing/propagation/TextMapAdapter.java
- opentracing-api/src/main/java/io/opentracing/propagation/TextMapExtract.java
- opentracing-api/src/main/java/io/opentracing/propagation/TextMapInject.java
- opentracing-api/src/main/java/io/opentracing/propagation/TextMapInjectAdapter.java
- opentracing-api/src/test/java/io/opentracing/propagation/BinaryAdaptersTest.java
- opentracing-api/src/test/java/io/opentracing/propagation/BuiltinFormatTest.java
- opentracing-api/src/test/java/io/opentracing/propagation/TextMapExtractAdapterTest.java
- opentracing-api/src/test/java/io/opentracing/propagation/TextMapInjectAdapterTest.java
- opentracing-mock/src/main/java/io/opentracing/mock/MockTracer.java
- opentracing-mock/src/test/java/io/opentracing/mock/MockTracerTest.java
- opentracing-testbed/src/test/java/io/opentracing/testbed/client_server/Client.java
- opentracing-testbed/src/test/java/io/opentracing/testbed/client_server/Server.java
- opentracing-testbed/src/test/java/io/opentracing/testbed/error_reporting/ErrorReportingTest.java
If we had separate formats for inject and extract this refactor would have been much cleaner.
This allows us to better avoid partially implementing the TextMap interface and throwing an exception for the other method.
Since Binary is a new addition, I applied a similar refactoring to that.
Closes #315.
> Split Inject and Extract Builtin interfaces

- README.md
- opentracing-api/src/main/java/io/opentracing/ScopeManager.java
- opentracing-api/src/main/java/io/opentracing/Tracer.java
- opentracing-mock/src/main/java/io/opentracing/mock/MockTracer.java
- opentracing-testbed/README.md
- opentracing-testbed/src/test/java/io/opentracing/testbed/active_span_replacement/ActiveSpanReplacementTest.java
- opentracing-testbed/src/test/java/io/opentracing/testbed/actor_propagation/ActorPropagationTest.java
- opentracing-testbed/src/test/java/io/opentracing/testbed/client_server/TestClientServerTest.java
- opentracing-testbed/src/test/java/io/opentracing/testbed/common_request_handler/HandlerTest.java
- opentracing-testbed/src/test/java/io/opentracing/testbed/concurrent_common_request_handler/Client.java
- opentracing-testbed/src/test/java/io/opentracing/testbed/concurrent_common_request_handler/Context.java
- opentracing-testbed/src/test/java/io/opentracing/testbed/concurrent_common_request_handler/HandlerTest.java
- opentracing-testbed/src/test/java/io/opentracing/testbed/concurrent_common_request_handler/README.md
- opentracing-testbed/src/test/java/io/opentracing/testbed/concurrent_common_request_handler/RequestHandler.java
- opentracing-testbed/src/test/java/io/opentracing/testbed/error_reporting/ErrorReportingTest.java
- opentracing-testbed/src/test/java/io/opentracing/testbed/late_span_finish/LateSpanFinishTest.java
- opentracing-testbed/src/test/java/io/opentracing/testbed/listener_per_request/ListenerTest.java
- opentracing-testbed/src/test/java/io/opentracing/testbed/multiple_callbacks/Client.java
- opentracing-testbed/src/test/java/io/opentracing/testbed/multiple_callbacks/MultipleCallbacksTest.java
- opentracing-testbed/src/test/java/io/opentracing/testbed/multiple_callbacks/README.md
- opentracing-testbed/src/test/java/io/opentracing/testbed/nested_callbacks/NestedCallbacksTest.java
- opentracing-testbed/src/test/java/io/opentracing/testbed/stateless_common_request_handler/Client.java
- opentracing-testbed/src/test/java/io/opentracing/testbed/stateless_common_request_handler/HandlerTest.java
- opentracing-testbed/src/test/java/io/opentracing/testbed/stateless_common_request_handler/README.md
- opentracing-testbed/src/test/java/io/opentracing/testbed/stateless_common_request_handler/RequestHandler.java
- opentracing-util/src/main/java/io/opentracing/util/AutoFinishScopeManager.java
- opentracing-util/src/test/java/io/opentracing/util/AutoFinishScopeManagerTest.java
Addresses #267 
1. `ScopeManager.active()` is deprecated.
2. Tests around it are kept, till we fully remove it.
3. Its usage is removed from `testbed` though.
4. Updated `AutoFinishScopeManager` (a rather exoteric manager) to also offer its capture/continue workflow without relying on a publicly visible `Scope`.
5. Added a test case showing the case when the even handler or request handler has no object to store the `Scope` object, being solved by using  a thread-local field.
Probably the important point is 5) - as it shows a concrete scenario that has historically prevented us from removing `active()` altogether. I'm hope this case is not over simplifying this requirement ;)
@opentracing/opentracing-java-maintainers please feel free to leave your opinion, as I'd like to have this …
> Deprecate ScopeManager.active()

- opentracing-api/src/main/java/io/opentracing/Tracer.java
- opentracing-mock/src/main/java/io/opentracing/mock/MockTracer.java
- opentracing-mock/src/test/java/io/opentracing/mock/MockTracerTest.java
- opentracing-noop/src/main/java/io/opentracing/noop/NoopTracer.java
- opentracing-util/src/main/java/io/opentracing/util/GlobalTracer.java
- opentracing-util/src/test/java/io/opentracing/util/GlobalTracerTest.java
Prior to 0.32, I decided to take a shot at this feature (as part of https://github.com/opentracing/specification/issues/130) - the change itself is actually minimal, and I'm guessing that this could be an easy-to-implement item for Tracer maintainers, but would definitely love some feedback.
Depending on how good or bad the changes are deemed, we might include this in the 0.32 Final Release ;)
PS - Was tempted to leave `MockTracer.close()` as no-op, but preferred to keep the invariant.
@yurishkuro @tylerbenson @austinlparker  @opentracing/opentracing-java-maintainers
> Make Tracer extends Closable.

- README.md
The README is now updated with the new Scope/Span usage, as well as mention of deprecation of automatic Span finish upon Scope close (and related members).
This is done prior to do a release (finally) ;)
> V0.32.0 README update

- opentracing-util/src/main/java/io/opentracing/util/GlobalTracer.java
This one does not really need to be synchronized.
The field itself is volatile and that is enough.
Probably being too pedantic on this, but it feels this is the correct thing to do ;)
@yurishkuro @sjoerdtalsma
> Do not make isRegistered() synchronized.

- opentracing-util/src/main/java/io/opentracing/util/AutoFinishScope.java
- opentracing-util/src/main/java/io/opentracing/util/AutoFinishScopeManager.java
The last fix before releasing 0.32 ;)
@yurishkuro
> Deprecate AutoFinishScopeManager

- CONTRIBUTING.md
- opentracing-api/src/main/java/io/opentracing/tag/Tags.java
Add `peer.address` tag according to [OpenTracing Specification Semantic Conventions v1.1](https://github.com/opentracing/specification/blob/master/semantic_conventions.md).
>  Add PEER_ADDRESS tag

- opentracing-mock/src/main/java/io/opentracing/mock/MockTracer.java
- opentracing-mock/src/test/java/io/opentracing/mock/MockTracerTest.java
- opentracing-testbed/src/test/java/io/opentracing/testbed/concurrent_common_request_handler/HandlerTest.java
> Add method finishedTraces to MockTracer.
